spring:
  application:
    name: knobot-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/knobot?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&characterSetResults=utf8mb4&connectionCollation=utf8mb4_unicode_ci
  mail:
    username: 3979892804@qq.com
    password: ${EMAIL_PASSWORD}
    host: smtp.qq.com
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          starttls:
            required: true
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: false
  data:
    redis:
      host: ${SERVER_IP}
      port: 6379
      database: 15
  config:
    import: application-ai.yml, application-oss.yml

server:
  port: 8080


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


# 邮件参数配置
mail:
  from-address: 3979892804@qq.com # 发送邮件的机器人
  to-address: 2023321332@qq.com # 作者邮件地址 - 接收用户反馈信息
  template: |
    <div style="font-family: Arial, sans-serif; line-height: 1.6;">
      <p><strong>问题反馈时间：</strong>%s</p>

      <p><strong>问题描述：</strong></p>
      <p>%s</p>

      <hr style="border: none; border-top: 1px solid #ccc; margin: 20px 0;">
      <p style="color: #666; font-size: 12px;">此邮件由系统自动发送，请勿直接回复。</p>
    </div>

# 文件上传方式
upload:
  way: oss # -local 本地上传 -oss 阿里云对象存储

# 日志地址
log:
  path: logs